config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from analytics.views import SalesView, SalesAjaxView
from products_billing.views import payment_method_view, payment_method_createview
from accounts.views import GuestRegisterView, CustomLoginView, CustomSignUpView
from products_carts.views import cart_detail_api_view
from products_addresses.views import checkout_address_create_view, checkout_address_reuse_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from products_orders.views import LibraryView


urlpatterns = [
    path('admin-2281953/', admin.site.urls),
    path('accounts/signup/', CustomSignUpView.as_view(), name='account_signup'),
    path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('analytics/sales/', SalesView.as_view(), name='sales-analytics'),
    path('analytics/sales/data/', SalesAjaxView.as_view(), name='sales-analytics-data'),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'), 
    path('library /', LibraryView.as_view(), name='library'), 
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'), 
    path('user/', include('accounts.urls')),
    path('orders/', include('products_orders.urls')),
    path('polls/', include('polls.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('blog2/', include('blog2.urls')),
    path('books/', include('books.urls')),
    path('organizer/', include('organizer.urls')),
    path('sublog/', include('sublog.urls')),
    path('doc/', include('doc.urls')),
    path('first_app/', include('first_app.urls')),
    path('companies/', include('companies.urls')),
    path('basic_app/', include('basic_app.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('products/cart/', include('products_carts.urls')),
    path('products/', include('products.urls')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

doc/urls.py
from django.urls import path, register_converter, re_path, include

from . import views, converters

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('2003/', views.special_case_2003, {'foo': 'barrrrr'}),
    re_path(r'^(?P<year>[0-9]{4})/$', views.year_archive, name='year-archive'),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
    path('year<yyyy:year>/<int:month>/<slug:slug>/', views.article_detail),
    path('blog/', views.page),
    path('blog/page<int:num>/', views.page),
    path('<int:num>/', include([
        path('history/', views.history),
        path('edit/', views.edit),]), {'foo': 'baaaaar'}),
    path('contact/', views.get_contact),
    path('upload/', views.upload_file),
]

groups/urls.py
from django.urls import path

from .import views

app_name = 'groups'
urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<slug:slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>/', views.LeaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

ssocial/urls.py
from django.urls import path

from . import views

app_name = 'ssocial'
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
]

ssocial/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'ssocial/index.html'

templates/ssocial/_base.html
{% extends '_base.html' %}
{% load static %}

{% block content %}
<div class='main-part-no'>
    <nav class=" navbar sticky-top ">
        <div class="container-fluid">
          <a class="mynav navbar-brand" href="{% url 'groups:all' %}">Star Social</a>
          <div class='d-flex'>
            {% if user.is_authenticated %}
            <a class='mynav nav-link-margin-right' href="{% url 'posts:for_user' user.username %}">@{{ user.username }}</a>
            <a class=' mynav nav-link-margin-right' href="{% url 'posts:all' %}">Posts</a>
            <a class='mynav nav-link-margin-right' href="{% url 'groups:all' %}">Groups</a>
            <a class='mynav nav-link-margin-right' href="{% url 'groups:create'  %}">New Group</a>
            <a class=' mynav ' href="{% url 'posts:create' %}">New Post</a>
          {% endif %}
        </div>
        </div>
    </nav>
    <div class='container mycontent'>   
        {% block contentt %}
        {% endblock contentt %}
    </div>
    <canvas id="canvas"></canvas>
</div>
<script type='text/javascript' src="{% static 'simplesocial/js/master.js' %}"></script>
{% endblock content %} 

templates/ssocial/index.html
{% extends 'ssocial/_base.html' %}

{% block contentt %}
    <h1>Welcome to Star Social!</h1>
{% endblock contentt %}