config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from analytics.views import SalesView, SalesAjaxView
from products_billing.views import payment_method_view, payment_method_createview
from accounts.views import GuestRegisterView, CustomLoginView, CustomSignUpView
from products_carts.views import cart_detail_api_view
from products_addresses.views import checkout_address_create_view, checkout_address_reuse_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from products_orders.views import LibraryView


urlpatterns = [
    path('admin-2281953/', admin.site.urls),
    path('accounts/signup/', CustomSignUpView.as_view(), name='account_signup'),
    path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('analytics/sales/', SalesView.as_view(), name='sales-analytics'),
    path('analytics/sales/data/', SalesAjaxView.as_view(), name='sales-analytics-data'),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'), 
    path('library /', LibraryView.as_view(), name='library'), 
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'), 
    path('user/', include('accounts.urls')),
    path('orders/', include('products_orders.urls')),
    path('polls/', include('polls.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('blog2/', include('blog2.urls')),
    path('books/', include('books.urls')),
    path('organizer/', include('organizer.urls')),
    path('sublog/', include('sublog.urls')),
    path('doc/', include('doc.urls')),
    path('first_app/', include('first_app.urls')),
    path('companies/', include('companies.urls')),
    path('basic_app/', include('basic_app.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('products/cart/', include('products_carts.urls')),
    path('products/', include('products.urls')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

doc/urls.py
from django.urls import path, register_converter, re_path, include

from . import views, converters

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('2003/', views.special_case_2003, {'foo': 'barrrrr'}),
    re_path(r'^(?P<year>[0-9]{4})/$', views.year_archive, name='year-archive'),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
    path('year<yyyy:year>/<int:month>/<slug:slug>/', views.article_detail),
    path('blog/', views.page),
    path('blog/page<int:num>/', views.page),
    path('<int:num>/', include([
        path('history/', views.history),
        path('edit/', views.edit),]), {'foo': 'baaaaar'}),
    path('contact/', views.get_contact),
    path('upload/', views.upload_file),
]

organizer/urls.py
from urllib.parse import urlparse
from django.urls import path, re_path
from django.views.generic import RedirectView, TemplateView

from . import views

app_name = 'organizer'
urlpatterns = [
    path('', RedirectView.as_view(
        pattern_name='sublog:post_list',
        permanent=False,
    )),
    path('about/', TemplateView.as_view(
        template_name='organizer/about.html'), name='about'),
    path('newslink/create/', views.NewsLinkCreate.as_view(), name='newslink_create'),
    path('newslink/update/<int:pk>/', views.NewsLinkUpdate.as_view(), name='newslink_update'),
    path('newslink/delete/<int:pk>/', views.NewsLinkDelete.as_view(), name='newslink_delete'),
    path('startup/', views.StartupList.as_view(), name='startup_list'),
    path('startup/create/', views.StartupCreate.as_view(), name='startup_create'),
    path('startup/<slug:slug>/', views.StartupDetail.as_view(), name='startup_detail'),
    path('startup/<slug:slug>/update/', views.StartupUpdate.as_view(), name='startup_update'),
    path('startup/<slug:slug>/delete/', views.StartupDelete.as_view(), name='startup_delete'),
    path('tag/', views.TagPageList.as_view(), name='tag_list'),
    path('tag/<int:page_number>/', views.TagPageList.as_view(), name='tag_page'),
    path('tag/create/', views.TagCreate.as_view(), name='tag_create'),
    path('tag/<slug:slug>/', views.TagDetail.as_view(), name='tag_detail'),
    path('tag/<slug:slug>/update/', views.TagUpdate.as_view(), name='tag_update'),
    path('tag/<slug:slug>/delete/', views.TagDelete.as_view(), name='tag_delete'),
]

organizer/models.py
from django.db import models
from django.urls import reverse

class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, 
                            unique=True, 
                            help_text='A label for URL config.')

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('organizer:tag_detail', 
                        kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer:tag_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse(
            'organizer:tag_delete',
            kwargs={'slug': self.slug}
        )

    class Meta:
        ordering = ['name']

class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config.'
    )
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer:startup_detail', 
                        kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer:startup_update', 
                        kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse(
            'organizer:startup_delete',
            kwargs={'slug': self.slug}
        )

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    slug = models.SlugField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE)
        
    def __str__(self):
        return '{}:{}'.format(
            self.startup, self.title
        )
    
    def get_absolute_url(self):
        return self.startup.get_absolute_url()

    def get_update_url(self):
        return reverse(
            'organizer:newslink_update',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'organizer:newslink_delete',
            kwargs={'pk': self.pk}
        )

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together=('slug', 'startup')

organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Tag, Startup, NewsLink

class SlugCleanMixin:

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError(
                'Slug may not be "create".'
            )
        return new_slug

class TagForm(SlugCleanMixin, forms.ModelForm):

    class Meta:
        model = Tag
        fields = ['name', 'slug']

    def clean_name(self):
        return self.cleaned_data['name'].lower()

    
class NewsLinkForm(forms.ModelForm):

    class Meta:
        model = NewsLink
        fields = ['title', 'pub_date', 'link', 'startup']
        
class StartupForm(SlugCleanMixin, forms.ModelForm):

    class Meta:
        model = Startup
        fields = ['name', 'slug', 'description', 'founded_date', 'contact', 'website', 'tags']

organizer/views.py
from ast import Delete
from django.core.paginator import (Paginator, 
                EmptyPage, PageNotAnInteger)
from django.views.generic import (
    CreateView, DeleteView, DetailView, UpdateView, View,
)
from django.shortcuts import (
    render, redirect, get_object_or_404)
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse, Http404
from django.urls import reverse_lazy, reverse

from .models import Tag, Startup, NewsLink
from .forms import TagForm, StartupForm, NewsLinkForm

class TagList(View):
    template_name = 'organizer/tag_list.html'

    def get(self, request):
        tags = Tag.objects.all()
        context = {
            'tag_list': tags
        }
        return render(
            request, self.template_name, context
        )

class TagPageList(View):
    paginate_by = 5
    template_name = 'organizer/tag_list.html'

    def get(self, request, page_number='a'):
        tags = Tag.objects.all()
        paginator = Paginator(tags, self.paginate_by)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            prev_url = reverse(
                'organizer:tag_page',
                args=(page.previous_page_number(),)
            )
        else:
            prev_url = None
        if page.has_next():
            next_url = reverse(
                'organizer:tag_page',
                args=(page.next_page_number(),)
            )
        else:
            next_url = None
        context = {
            'is_paginated': page.has_other_pages(),
            'next_page_url': next_url,
            'previous_page_url': prev_url,
            'paginator': paginator,
            'tag_list': page
        }
        return render(request, self.template_name, context)

class TagDetail(DetailView):
    model = Tag

class StartupList(View):
    page_kwarg = 'page'
    paginate_by = 5
    template_name = 'organizer/startup_list.html'

    def get(self, request):
        startups = Startup.objects.all()
        paginator = Paginator(startups, self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        if page.has_previous():
            prev_url = '?{pkw}={n}'.format(
                pkw=self.page_kwarg,
                n=page.previous_page_number()
            )
        else:
            prev_url = None
        if page.has_next():
            next_url = '?{pkw}={n}'.format(
                pkw=self.page_kwarg,
                n=page.next_page_number()
            )
        else:
            next_url = None
        context = {
                'is_paginated': page.has_other_pages(),
                'startup_list': page,
                'paginator': paginator,
                'previous_page_url': prev_url,
                'next_page_url': next_url,
                }
        return render(request, self.template_name, context)

class StartupDetail(DetailView):
    model = Startup



# def tag_create(request):
#     if request.method == 'POST':
#         form = TagForm(request.POST)
#         if form.is_valid():
#             new_tag = form.save()
#             return redirect(new_tag)
#     else:
#         form = TagForm()
#     return render(
#         request,
#         'organizer/tag_form.html',
#         {'form': form}
#     )

class TagCreate(CreateView):
    form_class = TagForm
    model = Tag

class TagUpdate(UpdateView):
    form_class = TagForm
    model = Tag
    template_name = 'organizer/tag_form_update.html'

class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('organizer:tag_list')

class StartupCreate(CreateView):
    form_class = StartupForm
    model = Startup

class StartupUpdate(UpdateView):
    form_class = StartupForm
    model = Startup
    template_name = 'organizer/startup_form_update.html'

class StartupDelete(DeleteView):
    model = Startup
    success_url = reverse_lazy('organizer:startup_list')

class NewsLinkCreate(CreateView):
    form_class = NewsLinkForm
    model = NewsLink

class NewsLinkUpdate(View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form_update.html'

    def get(self, request, pk):
        newslink = get_object_or_404(NewsLink, pk=pk)
        context = {
            'form': self.form_class(instance=newslink),
            'newslink': newslink,
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk
        )
        bound_form = self.form_class(
            request.POST, instance=newslink
        )
        if bound_form.is_valid():
            new_newslink=bound_form.save()
            return redirect(new_newslink)
        else:
            context = {
                'form': bound_form,
                'newslink': newslink
            }
            return render(
                request,
                self.template_name,
                context
            )

class NewsLinkDelete(View):

    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk
        )
        return render(
            request,
            'organizer/newslink_confirm_delete.html',
            {'newslink': newslink}
        )
    
    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk
        )
        startup = newslink.startup
        newslink.delete()
        return redirect(startup)

organizer/templates/organizer/about.html
{% extends 'organizer/_base.html' %}

{% block title %}
{{ block.super }} - About
{% endblock title %}

{% block contentt %}
{% endblock contentt %}

organizer/templates/organizer/base_organizer.html
{% extends 'organizer/_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'organizer/style.css' %}"
        type='text/css'>
{% endblock head %}

organizer/templates/organizer/newslink_confirm_delete.html
{% extends 'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Delete Newslink
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{{ newslink.get_delete_url }}" 
                method='post'>
                {% csrf_token %}
                <p>
                    Are you sure you want to delete
                    newslink  {{ newslink.name}}?
                </p>
                <a href="{{ newslink.get_absolute_url}}">Cancel</a>
                <button type='submit'>Delete Newslink</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/newslink_form.html
{% extends 'organizer/base_organizer.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{% url 'organizer:newslink_create' %}" 
                method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit'>Link Article</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/newslink_form_update.html
{% extends 'organizer/base_organizer.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Update News Link
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{{ newslink.get_update_url }}" 
                method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit'>Update News Link</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/startup_confirm_delete.html
{% extends 'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Delete Startup
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{{ startup.get_delete_url }}" 
                method='post'>
                {% csrf_token %}
                <p>
                    Are you sure you want to delete
                    startup  {{ startup.name}}?
                </p>
                <a href="{{ startup.get_absolute_url}}">Cancel</a>
                <button type='submit'>Delete Tag</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/startup_detail.html
{% extends 'organizer/base_organizer.html' %}

{% block contentt %}
<article>
    <h2>{{ startup.name }}</h2>
    <ul>
        <li>
            <a href="{{ startup.get_update_url}}">
                Edit Startup
            </a>
        </li>
        <li>
            <a href="{{ startup.get_delete_url}}">
                Delete Startup
            </a>
        </li>
    </ul>
    <dl>
        <dt>Date Founded</dt>
            <dd>{{ startup.founded_date|date:'F jS, Y' }}</dd>
        <dt>Website</dt>
            <dd>{{ startup.website|urlize }}</dd>
        <dt>Contact</dt>
            <dd>{{ startup.contact}}</dd>
        <dt>Tag{{ startup.tags.count|pluralize}}</dt>
            {% for tag in startup.tags.all %}
                <dd>
                    <a href="{{ tag.get_absolute_url }}">
                        {{ tag.name|title}}
                    </a>
                </dd>
            {% endfor %}
    </dl>

    {{ startup.description|linebreaks }}
    
    {% if startup.newslink_set.all %}
        <section>
            <h3>Recent News</h3>
            <ul>
                {% for newslink in startup.newslink_set.all %}
                    <li>
                        <a href="{{ newslink.link }}">
                            {{ newslink.title|title }}
                        </a><br>
                        <a href="{{ newslink.get_update_url}}">
                            Edit Link
                        </a>
                        <a href="{{ newslink.get_delete_url}}">
                            Delete Link
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    <a href="{% url 'organizer:newslink_create' %}">
        Add Article
    </a>
    {% if startup.blog_posts.all %}
        <section>
            <h3>Blog Post{{ startup.blog_posts.count|pluralize}}</h3>
            <ul>
                {% for post in startup.blog_posts.all %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title|title}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
</article>
{% endblock contentt %}

organizer/templates/organizer/startup_form.html
{% extends 'organizer/base_organizer.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{% url 'organizer:startup_create' %}" 
                method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit'>Create Startup</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/startup_form_update.html
{% extends 'organizer/base_organizer.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Update Startup
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{{ startup.get_update_url }}" 
                method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit'>Update Startup</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/startup_list.html
{% extends 'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Startups
{% endblock title %}

{% block contentt %}
    <h2>Startup List</h2>
    <div>
        <a href="{% url 'organizer:startup_create' %}">
            Create New Startup
        </a>
    </div>
    <ul>
        {% for startup in startup_list %}
            <li>
                <a href="{{ startup.get_absolute_url }}">
                    {{ startup.name }}
                </a><br>
                <a href="{{ startup.get_update_url }}">
                    Edit Startup
                </a><br>
                <a href="{{ startup.get_delete_url }}">
                    Delete Startup
                </a>
            </li>
        {% empty %}
            <li><em>No Startups Available</em></li>
        {% endfor %}
    </ul>
    <hr>
    {% if is_paginated %}
        <ul>
            {% if previous_page_url %}
                <li>
                    <a href="{{ previous_page_url }}">
                        Previous</a>
                </li>
            {% endif %}
            {% if next_page_url %}
                <li>
                    <a href="{{ next_page_url }}">
                        Next</a>
                </li>
            {% endif %}
            <li>
                Page {{ startup_list.number }}
                of {{ paginator.num_pages }}
            </li>
        </ul>
    {% endif %}
{% endblock contentt %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends 'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{{ tag.get_delete_url }}" 
                method='post'>
                {% csrf_token %}
                <p>
                    Are you sure you want to delete
                    tag  {{ tag.name}}?
                </p>
                <a href="{{ tag.get_absolute_url}}">Cancel</a>
                <button type='submit'>Delete Tag</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/tag_detail.html
{% extends 'organizer/base_organizer.html' %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock title %}

{% block contentt %}
    <h2>{{ tag.name|title }}</h2>
    <ul>
        <li>
            <a href="{{ tag.get_update_url }}">
                Edit Tag
            </a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{{ tag.get_delete_url }}">
                Delete Tag
            </a>
        </li>
    </ul>
    {% if tag.startup_set.all %}
        <section>
            <h3>Startup{{ tag.startup_set.count|pluralize}}</h3>
            <p>
                Tag is associated with
                {{ tag.startup_set.count }}
                startup{{ tag.startup_set.count|pluralize}}.
            </p>
            <ul>
                {% for startup in tag.startup_set.all %}
                    <li>
                        <a href="{{ startup.get_absolute_url }}">
                            {{ startup.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {% if tag.blog_posts.all %}
        <section>
            <h3>Blog Post{{ tag.blog_posts.count|pluralize}}</h3>
            <ul>
                {% for post in tag.blog_posts.all %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
    {% endif %}
{% endblock contentt %}

organizer/templates/organizer/tag_form.html
{% extends 'organizer/base_organizer.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{% url 'organizer:tag_create' %}" 
                method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit'>Create Tag</button>
            </form>
        </div>
    </div>
{% endblock contentt %}

organizer/templates/organizer/tag_form_update.html
{% extends 'organizer/base_organizer.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock title %}

{% block contentt %}
    <div>
        <div>
            <form 
                action="{{ tag.get_update_url }}" 
                method='post'>
                {% csrf_token %}
                {{ form|crispy }}
                <button type='submit'>Update Tag</button>
            </form>
        </div>
    </div>
{% endblock contentt %}