blog2/urls.py
from django.urls import path

from .import views

app_name = 'blog2'
urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/create/', views.PostCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from analytics.views import SalesView, SalesAjaxView
from products_billing.views import payment_method_view, payment_method_createview
from accounts.views import GuestRegisterView, CustomLoginView, CustomSignUpView
from products_carts.views import cart_detail_api_view
from products_addresses.views import checkout_address_create_view, checkout_address_reuse_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from products_orders.views import LibraryView


urlpatterns = [
    path('admin-2281953/', admin.site.urls),
    path('accounts/signup/', CustomSignUpView.as_view(), name='account_signup'),
    path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
    path('accounts/', include('allauth.urls')),
    path('analytics/sales/', SalesView.as_view(), name='sales-analytics'),
    path('analytics/sales/data/', SalesAjaxView.as_view(), name='sales-analytics-data'),
    path('billing/payment-method/create/', payment_method_createview, name='billing-payment-method-endpoint'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'), 
    path('library /', LibraryView.as_view(), name='library'), 
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'), 
    path('user/', include('accounts.urls')),
    path('orders/', include('products_orders.urls')),
    path('polls/', include('polls.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
    path('blog2/', include('blog2.urls')),
    path('books/', include('books.urls')),
    path('organizer/', include('organizer.urls')),
    path('sublog/', include('sublog.urls')),
    path('doc/', include('doc.urls')),
    path('first_app/', include('first_app.urls')),
    path('companies/', include('companies.urls')),
    path('basic_app/', include('basic_app.urls')),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('products/cart/', include('products_carts.urls')),
    path('products/', include('products.urls')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

doc/urls.py
from django.urls import path, register_converter, re_path, include

from . import views, converters

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('2003/', views.special_case_2003, {'foo': 'barrrrr'}),
    re_path(r'^(?P<year>[0-9]{4})/$', views.year_archive, name='year-archive'),
    re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.month_archive),
    path('year<yyyy:year>/<int:month>/<slug:slug>/', views.article_detail),
    path('blog/', views.page),
    path('blog/page<int:num>/', views.page),
    path('<int:num>/', include([
        path('history/', views.history),
        path('edit/', views.edit),]), {'foo': 'baaaaar'}),
    path('contact/', views.get_contact),
    path('upload/', views.upload_file),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

blog2/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

class Post(models.Model):
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)
    
    def get_absolute_url(self):
        return reverse('blog2:post_detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog2:post_list')

    def __str__(self):
        return self.text

posts/models.py
import misaka
from django.db import models
from django.urls import reverse
from django.conf import settings
from groups.models import Group
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts', null=True, blank=True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username,
                                                'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

blog2/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass', 'placeholder': 'type your title'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'}),
        }

blog2/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls.base import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView,
                                    DeleteView, UpdateView)
from django.db.models import Q

from .models import Post, Comment
from .forms import CommentForm, PostForm

class AboutView(TemplateView):
    template_name = 'blog2/about.html'

class PostListView(ListView):
    model = Post
    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(Q(published_date__isnull=False) | Q(published_date__isnull=True, author=self.request.user)).order_by('created_date')

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = PostForm
    model = Post
    
    def test_func(self):
        return self.get_object().author == self.request.user

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog2:post_list')

    def test_func(self):
        return self.get_object().author == self.request.user

class DraftListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog2/post_draft_list.html'
    context_object_name = 'posts'
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True, author=self.request.user).order_by('created_date')
    

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog2:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog2/comment_form.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog2:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog2:post_detail', pk=post_pk)

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog2:post_detail', pk=pk)

posts/views.py
from django.db.models.query_utils import select_related_descend
from django.forms import forms
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from django.contrib.auth import get_user_model
from django.contrib import messages

from . import models
from . import forms

User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username=self.request.user.username)
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
    
class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.request.user.username)

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

blog2/templates/blog2/_base.html
{% extends '_base.html' %}

{% block content %}
<div class='main-part-no loader'>
  <nav class="navbar  sticky-top navbar-expand-lg navbar-light bg-light ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog2:post_list' %}">My Blog2</a>
      <a href="{% url 'blog2:about' %}">About</a>
      {% if user.is_authenticated %}
        <a href="{% url 'blog2:post_new' %}">New Post</a>
        <a href="{% url 'blog2:post_draft_list' %}">Drafts</a>
      {% endif %}
    </div>
  </nav>
  <div class='main-part'>
      {% block contentt %}
      {% endblock contentt %}
  </div>
</div>
{% endblock content %}

blog2/templates/blog2/about.html
{% extends 'blog2/_base.html' %}

{% block contentt %}
    <h1>About this company</h1>
    <p>Thanks for checking</p>
{% endblock contentt %}

blog2/templates/blog2/comment_form.html
{% extends 'blog2/_base.html' %}
{% load crispy_forms_tags %}

{% block contentt %}
    <h1>New Comment</h1>
    <form class='post-form' method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn-margin-up save btn btn-success'>Post Comment</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock contentt %}

blog2/templates/blog2/post_confirm_delete.html
{% extends 'blog2/_base.html' %}

{% block contentt %}
    <form method='post'>
        {% csrf_token %}
        <p>Are you cure you want to delete {{ object }}?</p>
        <input type="submit" class='btn btn-danger' value='Confirm'>
    </form>
{% endblock contentt %}

blog2/templates/blog2/post_detail.html
{% extends 'blog2/_base.html' %}

{% block contentt %}
<h1 class='posttitle loader'>{{ post.title }}</h1>

{% if post.published_date %}
    <div class="date postdate">
        {{ post.published_date }}
    </div>

{% else %}
    <a class="btn btn-success" href="{% url 'blog2:post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<p class='postcontent' >{{ post.text|safe|linebreaksbr }}</p>


{% if user.is_authenticated and post.author == user%}
  <a class="btn btn-primary" href="{% url 'blog2:post_edit' pk=post.pk %}"><span class="bi bi-pencil-fill"></span></a>
  <a class="btn btn-primary" href="{% url 'blog2:post_remove' pk=post.pk %}"><span class="bi bi-trash-fill"></span></a>
{% endif %}



<hr>
<a class="btn btn-primary btn-comment" href="{% url 'blog2:add_comment_to_post' pk=post.pk %}">Add comment</a>
<div class="container">


{% for comment in post.comments.all %}
<br>
{% if comment.approved_comment or post.author == user%}

      {{ comment.created_date }}
      {% if not comment.approved_comment and post.author == user %}
          <a class="btn btn-primary" href="{% url 'blog2:comment_remove' pk=comment.pk %}"><span class="bi bi-trash-fill"></span></a>
          <a class="btn btn-primary" href="{% url 'blog2:comment_approve' pk=comment.pk %}"><span class="bi bi-check-circle-fill"></span></a>
      {% endif %}

  <p>{{ comment.text|safe|linebreaks }}</p>
  <p>Posted by: <strong>{{ comment.author }}</strong></p>

{% endif %}
{% empty %}
<p>No comments posted.</p>
{% endfor %}
</div>
{% endblock contentt %}

blog2/templates/blog2/post_draft_list.html
{% extends 'blog2/_base.html' %}

{% block contentt %}
    {% for post in posts  %}
        <div class='post'>
            <h1><a href="{% url 'blog2:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <p class='date'>Created: {{ post.created_date}}</p>
            <p>{{ post.text|safe|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock contentt %}

blog2/templates/blog2/post_form.html
{% extends 'blog2/_base.html' %}
{% load crispy_forms_tags %}

{% block contentt %}
    {% if form.instance.pk %}
    <h1>Edit Post</h1>
    {% else %}
    <h1>New Post</h1>
    {% endif %}
    <form class='post-form' method='post'>
        {% csrf_token %}
        {{form|crispy}}
        <button type='submit' class=' btn-margin-up save btn btn-success'>Save</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock contentt %}

blog2/templates/blog2/post_list.html
{% extends 'blog2/_base.html' %}

{% block contentt %}
    <div class='centerstage'>
        {% for post in post_list %}
        <div class='post'>
            <h1><a href="{% url 'blog2:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <div class='date'>
                <p>Published on: {{ post.published_date}}</p>
            </div>
            <a href="{% url 'blog2:post_detail' post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        </div>
        {% endfor %}
    </div>
{% endblock contentt %}